//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iTellerBranch.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountStament
    {
        public int Id { get; set; }
        public string Narration { get; set; }
        public Nullable<System.DateTime> ValDate { get; set; }
        public string ExpenseLine { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public Nullable<decimal> Debit { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<bool> Approved { get; set; }
        public Nullable<int> AccountId { get; set; }
    
        public virtual CustomerDetails CustomerDetails { get; set; }
    }
}
