//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iTellerBranch.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class CallOverMode
    {
        public int ID { get; set; }
        public string ChequeNumber { get; set; }
        public string SortCode { get; set; }
        public string AccNumber { get; set; }
        public string TranType { get; set; }
        public string WhoApproved { get; set; }
        public Nullable<System.DateTime> DateOfApproval { get; set; }
        public byte[] frontImage { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> RemoteLodgementRecordID { get; set; }
        public string scanbranchCode { get; set; }
        public string scannerID { get; set; }
    }
}
