//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iTellerBranch.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashDenomination
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CashDenomination()
        {
            this.Denomination = new HashSet<Denomination>();
            this.GLAccountSetup = new HashSet<GLAccountSetup>();
            this.TillTransfer = new HashSet<TillTransfer>();
            this.TillTransferIMAL = new HashSet<TillTransferIMAL>();
        }
    
        public int ID { get; set; }
        public string SubunitName { get; set; }
        public Nullable<int> RelationshipUnit { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string Currency { get; set; }
        public Nullable<int> CurrencyCode { get; set; }
        public string Abbrev { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Denomination> Denomination { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GLAccountSetup> GLAccountSetup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TillTransfer> TillTransfer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TillTransferIMAL> TillTransferIMAL { get; set; }
    }
}
