//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iTellerBranch.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashReceipt
    {
        public int Id { get; set; }
        public Nullable<long> TranId { get; set; }
        public string POSId { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string AccountNo { get; set; }
        public string AccountTitle { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string FooterMessage { get; set; }
        public string Ref { get; set; }
        public Nullable<int> Printed { get; set; }
        public string AmountInWord { get; set; }
        public string Currency { get; set; }
        public string TellerName { get; set; }
        public string TransType { get; set; }
    }
}
