//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iTellerBranch.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class CautionSignatures
    {
        public int Id { get; set; }
        public Nullable<int> Idfield { get; set; }
        public string Signatory1 { get; set; }
        public string Designation1 { get; set; }
        public byte[] Sign1 { get; set; }
        public string Signatory2 { get; set; }
        public string Designation2 { get; set; }
        public byte[] Sign2 { get; set; }
    }
}
