//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iTellerBranch.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChequeDetailsCheckLog
    {
        public int Id { get; set; }
        public string ChequeNumber { get; set; }
        public string SortCode { get; set; }
        public string AcctNumber { get; set; }
        public string TranType { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string PresentingBankSortcode { get; set; }
        public Nullable<bool> Processed { get; set; }
        public string SessionId { get; set; }
        public Nullable<System.DateTime> CaptureFileDate { get; set; }
        public string CaptureFileTime { get; set; }
        public Nullable<bool> Cautioned { get; set; }
        public Nullable<long> ChequeRef { get; set; }
        public Nullable<System.DateTime> ScanDate { get; set; }
        public Nullable<bool> Uploaded { get; set; }
        public Nullable<System.DateTime> UploadedDate { get; set; }
        public Nullable<bool> Returned { get; set; }
        public Nullable<System.DateTime> ReturnedDate { get; set; }
        public Nullable<int> ReturnSession { get; set; }
        public string ReturnCustomerAccNo { get; set; }
        public string ReturnReason { get; set; }
        public string KioskID { get; set; }
        public Nullable<int> TransID { get; set; }
    }
}
