//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iTellerBranch.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cheque_Template
    {
        public int Template_Code { get; set; }
        public string Template_Name { get; set; }
        public Nullable<int> DateX { get; set; }
        public Nullable<int> DateY { get; set; }
        public Nullable<int> AmountX { get; set; }
        public Nullable<int> AmountY { get; set; }
        public Nullable<int> Amount_WordX { get; set; }
        public Nullable<int> Amount_WordY { get; set; }
        public Nullable<int> BeneficiaryX { get; set; }
        public Nullable<int> BeneficiaryY { get; set; }
        public Nullable<int> DateH { get; set; }
        public Nullable<int> DateW { get; set; }
        public Nullable<int> AmountH { get; set; }
        public Nullable<int> AmountW { get; set; }
        public Nullable<int> Amount_WordH { get; set; }
        public Nullable<int> Amount_WordW { get; set; }
        public Nullable<int> BeneficiaryH { get; set; }
        public Nullable<int> BeneficiaryW { get; set; }
        public string Amount_Font_Name { get; set; }
        public Nullable<int> Amount_font_size { get; set; }
        public string Amount_Font_Type { get; set; }
        public string Word_Font_Name { get; set; }
        public Nullable<int> Word_font_size { get; set; }
        public string Word_Font_Type { get; set; }
        public string Date_Font_Name { get; set; }
        public Nullable<int> Date_font_size { get; set; }
        public string Date_Font_Type { get; set; }
        public string Bene_Font_Name { get; set; }
        public Nullable<int> Bene_font_size { get; set; }
        public string Bene_Font_Type { get; set; }
        public Nullable<int> Sign1_top { get; set; }
        public Nullable<int> Sign2_top { get; set; }
        public Nullable<int> Sign3_top { get; set; }
        public Nullable<int> Sign4_top { get; set; }
        public Nullable<int> Sign1_left { get; set; }
        public Nullable<int> Sign2_left { get; set; }
        public Nullable<int> Sign3_left { get; set; }
        public Nullable<int> Sign4_left { get; set; }
        public Nullable<decimal> Ref_Top { get; set; }
        public Nullable<decimal> Ref_Left { get; set; }
        public Nullable<int> Ref_Height { get; set; }
        public Nullable<int> Ref_Width { get; set; }
        public string Company_Font_Name { get; set; }
        public Nullable<int> Company_Font_Size { get; set; }
        public string Company_Font_Type { get; set; }
        public Nullable<decimal> Company_Top { get; set; }
        public Nullable<decimal> Company_Left { get; set; }
        public string Annotation_Font_Name { get; set; }
        public Nullable<int> Annotation_Font_Size { get; set; }
        public string Annotation_Font_Type { get; set; }
        public Nullable<decimal> Annotation_Top { get; set; }
        public Nullable<decimal> Annotation_Left { get; set; }
        public decimal Cheque_Height { get; set; }
        public string Reference_Font_Name { get; set; }
        public Nullable<int> Reference_Font_Size { get; set; }
        public string Reference_Font_Type { get; set; }
        public Nullable<int> Code_LineX { get; set; }
        public Nullable<int> Code_LineY { get; set; }
        public Nullable<int> Code_Font_Size { get; set; }
        public Nullable<decimal> Code_Top { get; set; }
        public Nullable<decimal> Code_Left { get; set; }
        public string Code_font_name { get; set; }
        public string Code_font_Type { get; set; }
        public Nullable<decimal> MICR_Top { get; set; }
        public Nullable<decimal> MICR_Left { get; set; }
        public Nullable<decimal> MICR_Width { get; set; }
        public Nullable<decimal> MICR_Height { get; set; }
        public string MICR_font_name { get; set; }
        public Nullable<int> MICR_font_size { get; set; }
        public string MICR_font_type { get; set; }
        public Nullable<decimal> Embossment_Top { get; set; }
        public Nullable<decimal> Embossment_Left { get; set; }
        public Nullable<decimal> Embossment_Width { get; set; }
        public Nullable<int> Embossment_Height { get; set; }
        public string Embossment_Font_Name { get; set; }
        public string Embossment_Font_Type { get; set; }
        public Nullable<int> Embossment_Font_Size { get; set; }
        public Nullable<decimal> Stub_Amt_Top { get; set; }
        public Nullable<decimal> Stub_Amt_Left { get; set; }
        public Nullable<decimal> Stub_Amt_Width { get; set; }
        public Nullable<decimal> Stub_Amt_Height { get; set; }
        public Nullable<decimal> Stub_Date_Top { get; set; }
        public Nullable<decimal> Stub_Date_Left { get; set; }
        public Nullable<decimal> Stub_Date_Width { get; set; }
        public Nullable<decimal> Stub_Date_Height { get; set; }
        public Nullable<decimal> Stub_Bene_Top { get; set; }
        public Nullable<decimal> Stub_Bene_Left { get; set; }
        public Nullable<decimal> Stub_Bene_Width { get; set; }
        public Nullable<decimal> Stub_Bene_Height { get; set; }
        public Nullable<bool> Print_Stub { get; set; }
        public Nullable<decimal> cheque_width { get; set; }
        public Nullable<decimal> artworkX { get; set; }
        public Nullable<decimal> artworkY { get; set; }
        public Nullable<decimal> artworkHeight { get; set; }
        public Nullable<decimal> artworkWidth { get; set; }
        public Nullable<int> sign1_width { get; set; }
        public Nullable<int> sign1_height { get; set; }
        public Nullable<int> sign2_width { get; set; }
        public Nullable<int> sign2_height { get; set; }
        public Nullable<int> sign3_width { get; set; }
        public Nullable<int> sign3_height { get; set; }
        public Nullable<int> sign4_width { get; set; }
        public Nullable<int> sign4_height { get; set; }
    }
}
