//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iTellerBranch.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChequeAudit
    {
        public int ID { get; set; }
        public string chequeNumber { get; set; }
        public string userid { get; set; }
        public string reasons { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string idfield { get; set; }
        public string IPAddress { get; set; }
        public string servicePointID { get; set; }
        public string ClientID { get; set; }
    }
}
