//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iTellerBranch.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChequeImages
    {
        public int ID { get; set; }
        public long cheque_ref { get; set; }
        public byte[] frontImage { get; set; }
        public byte[] rearImage { get; set; }
        public Nullable<bool> commited { get; set; }
        public string machineName { get; set; }
        public Nullable<bool> isnax { get; set; }
        public string presentingbanksortcode { get; set; }
        public Nullable<bool> uploaded { get; set; }
        public Nullable<System.DateTime> uploadedDate { get; set; }
        public byte[] frontImage2 { get; set; }
    }
}
