//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iTellerBranch.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChequeDump
    {
        public long idfield { get; set; }
        public string ChequeNumber { get; set; }
        public string SortCode { get; set; }
        public string AccNumber { get; set; }
        public string TranType { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string PresentingBankSortcode { get; set; }
        public Nullable<bool> locked { get; set; }
        public Nullable<System.DateTime> scanDate { get; set; }
        public Nullable<int> batchID { get; set; }
        public string kioskID { get; set; }
        public Nullable<long> transID { get; set; }
        public Nullable<System.DateTime> captureDateTime { get; set; }
        public string checkingOfficer { get; set; }
        public Nullable<System.DateTime> checkingTime { get; set; }
        public string approvingOfficer { get; set; }
        public Nullable<System.DateTime> approvingTime { get; set; }
        public Nullable<bool> cautioned { get; set; }
        public Nullable<decimal> sessionid { get; set; }
        public Nullable<System.DateTime> valueDate { get; set; }
        public Nullable<int> approved { get; set; }
        public Nullable<int> status { get; set; }
        public string returnReason { get; set; }
        public Nullable<int> isInward { get; set; }
        public Nullable<System.DateTime> valueDateCaptured { get; set; }
        public Nullable<int> rejected { get; set; }
        public Nullable<bool> posted { get; set; }
        public Nullable<byte> postCount { get; set; }
        public Nullable<bool> notifiedFailure { get; set; }
        public Nullable<bool> sent2Clearing { get; set; }
        public string servicePointID { get; set; }
        public string depositor { get; set; }
        public string phoneno { get; set; }
        public Nullable<int> currencyCode { get; set; }
        public Nullable<System.DateTime> chequeDate { get; set; }
        public Nullable<int> Processed { get; set; }
        public string CaptureFileTime { get; set; }
        public Nullable<System.DateTime> CaptureFileDate { get; set; }
        public string scanBranchSortCode { get; set; }
        public string ChequeOperation_type { get; set; }
        public string Narration { get; set; }
        public Nullable<int> floatDays { get; set; }
        public Nullable<int> foreignId { get; set; }
        public string disapprovalComment { get; set; }
        public Nullable<int> callovermodestatus { get; set; }
        public bool MailStatus { get; set; }
        public string clientID { get; set; }
        public string LockID { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<long> msgid { get; set; }
        public string ItemSeqNumber { get; set; }
        public Nullable<bool> accepted { get; set; }
        public Nullable<bool> IsSpecialSession { get; set; }
        public string CheckDigit { get; set; }
        public string ExpiryDate { get; set; }
        public string PostingFileBatch { get; set; }
        public string CaptureFileBatch { get; set; }
        public string CBABeneficiary { get; set; }
        public Nullable<int> Match { get; set; }
    }
}
