//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iTellerBranch.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChequesForCashWithdrawal
    {
        public int Id { get; set; }
        public string ChequeNumber { get; set; }
        public string SortCode { get; set; }
        public string AcctNumber { get; set; }
        public string TranType { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string PresentingBankSortcode { get; set; }
        public Nullable<bool> Locked { get; set; }
        public long Idfield { get; set; }
        public Nullable<System.DateTime> ScanDate { get; set; }
        public Nullable<int> BatchID { get; set; }
        public string KioskID { get; set; }
        public Nullable<int> TransID { get; set; }
        public Nullable<System.DateTime> CaptureDateTime { get; set; }
        public string CheckingOfficer { get; set; }
        public Nullable<System.DateTime> CheckingTime { get; set; }
        public string ApprovingOfficer { get; set; }
        public Nullable<System.DateTime> ApprovingTime { get; set; }
        public Nullable<bool> Cautioned { get; set; }
        public Nullable<decimal> SessionId { get; set; }
        public Nullable<System.DateTime> ValueDate { get; set; }
        public Nullable<int> Approved { get; set; }
        public Nullable<int> Status { get; set; }
        public string ReturnReason { get; set; }
        public Nullable<int> IsInward { get; set; }
        public Nullable<System.DateTime> ValueDateCaptured { get; set; }
        public Nullable<int> Rejected { get; set; }
        public Nullable<bool> Posted { get; set; }
        public Nullable<byte> PostCount { get; set; }
        public Nullable<bool> NotifiedFailure { get; set; }
        public Nullable<bool> Sent2Clearing { get; set; }
        public string ServicePointID { get; set; }
        public string Depositor { get; set; }
        public string PhoneNo { get; set; }
        public Nullable<int> CurrencyCode { get; set; }
        public Nullable<System.DateTime> ChequeDate { get; set; }
        public bool Processed { get; set; }
        public string CaptureFileTime { get; set; }
        public Nullable<System.DateTime> CaptureFileDate { get; set; }
        public int CashTranID { get; set; }
    }
}
