//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iTellerBranch.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class chq_bene
    {
        public long cheque_ref { get; set; }
        public string acct_no { get; set; }
        public string beneficiary { get; set; }
        public string remarks { get; set; }
        public string presentingbanksortcode { get; set; }
        public string beneficiary_bvn { get; set; }
        public Nullable<System.DateTime> chequedate { get; set; }
        public string drawer { get; set; }
        public string payer_bvn { get; set; }
        public string MICRRepair { get; set; }
    }
}
