//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iTellerBranch.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientScanners
    {
        public string ClientID { get; set; }
        public string ScannerID { get; set; }
        public string ScannerTag { get; set; }
        public string ScannerType { get; set; }
        public Nullable<bool> Approved { get; set; }
        public string DisapprovalReason { get; set; }
    }
}
