//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iTellerBranch.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Currency
    {
        public int Id { get; set; }
        public int Code { get; set; }
        public string Currency1 { get; set; }
        public string Abbrev { get; set; }
        public string Country { get; set; }
    }
}
