//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iTellerBranch.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class customerMaster
    {
        public int Id { get; set; }
        public string AccountNo { get; set; }
        public string AccountName { get; set; }
        public string Email { get; set; }
        public string PhoneNo { get; set; }
        public Nullable<decimal> Bookbalance { get; set; }
        public Nullable<decimal> Availablebalance { get; set; }
        public string Accountofficer { get; set; }
        public string BranchCode { get; set; }
        public Nullable<System.DateTime> OpenDate { get; set; }
        public string AccountStatus { get; set; }
        public string Accountofficer_email { get; set; }
        public string Accountofficer_fullname { get; set; }
        public string Operatinginstructions { get; set; }
        public string AccountType { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string CurrencyCode { get; set; }
        public string Currency { get; set; }
        public string Abbrev { get; set; }
        public Nullable<bool> ValidForClearingCheque { get; set; }
        public string customerId { get; set; }
    }
}
