//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iTellerBranch.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiscountedTreasuryProduct
    {
        public int Id { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string AccountType { get; set; }
        public Nullable<bool> Discounted { get; set; }
        public Nullable<decimal> WHTMinAmt { get; set; }
        public Nullable<bool> Tenured { get; set; }
        public Nullable<decimal> MinTaxablePrincipal { get; set; }
        public string CBAProductCode { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public string WHTPayableAccount { get; set; }
        public string InterestPenaltyAccount { get; set; }
    }
}
