//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iTellerBranch.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class FixedInwardChequedump
    {
        public int ID { get; set; }
        public long itemid { get; set; }
        public string PreBankSeqNumber { get; set; }
        public string PayBankRoutNumber { get; set; }
        public string AccountNumber { get; set; }
        public string TransactionCode { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<decimal> ItemAmount { get; set; }
        public string presentingBankSortCode { get; set; }
        public Nullable<System.DateTime> presentmentDate { get; set; }
        public string Beneficiary { get; set; }
        public Nullable<bool> confirmedAccountMandate { get; set; }
        public Nullable<bool> confirmedFundsBalance { get; set; }
        public Nullable<bool> confirmedCheque { get; set; }
        public Nullable<long> DownloadBatchId { get; set; }
        public Nullable<System.DateTime> Settlementdatetime { get; set; }
        public string CheckDigit { get; set; }
        public string ExpiryDate { get; set; }
    }
}
