//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iTellerBranch.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class InwardChequeImage
    {
        public int ID { get; set; }
        public string ChequeNumber { get; set; }
        public string SortCode { get; set; }
        public string AccNumber { get; set; }
        public string TranType { get; set; }
        public string Sessionid { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string PresentingBankSortcode { get; set; }
        public byte[] FrontImage { get; set; }
        public byte[] FrontImage2 { get; set; }
        public byte[] RearImage { get; set; }
        public Nullable<bool> Processed { get; set; }
        public Nullable<System.DateTime> CaptureFileDate { get; set; }
        public string CaptureFileTime { get; set; }
        public Nullable<bool> cautioned { get; set; }
        public decimal cheque_ref { get; set; }
        public Nullable<System.DateTime> scanDate { get; set; }
        public Nullable<bool> returned { get; set; }
        public Nullable<System.DateTime> returnedDate { get; set; }
        public Nullable<int> returnSession { get; set; }
        public string returnCustomerAccNo { get; set; }
        public string returnReason { get; set; }
        public Nullable<System.DateTime> presentmentDate { get; set; }
        public Nullable<long> DownloadBatchId { get; set; }
        public byte[] QRCode { get; set; }
    }
}
