//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iTellerBranch.Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BranchConsoleEntities : DbContext
    {
        public BranchConsoleEntities()
            : base("name=BranchConsoleEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Audit> Audit { get; set; }
        public virtual DbSet<Branches> Branches { get; set; }
        public virtual DbSet<CallOverMode> CallOverMode { get; set; }
        public virtual DbSet<CashDenomination> CashDenomination { get; set; }
        public virtual DbSet<CashierBalancing> CashierBalancing { get; set; }
        public virtual DbSet<CashReceipt> CashReceipt { get; set; }
        public virtual DbSet<CashTransactions> CashTransactions { get; set; }
        public virtual DbSet<CautionExemption> CautionExemption { get; set; }
        public virtual DbSet<ChequeAudit> ChequeAudit { get; set; }
        public virtual DbSet<ChequeDump> ChequeDump { get; set; }
        public virtual DbSet<ChequeImages> ChequeImages { get; set; }
        public virtual DbSet<ChequeLodgement> ChequeLodgement { get; set; }
        public virtual DbSet<chequeStatus> chequeStatus { get; set; }
        public virtual DbSet<customerMaster> customerMaster { get; set; }
        public virtual DbSet<Denomination> Denomination { get; set; }
        public virtual DbSet<DocumentaryEvidence> DocumentaryEvidence { get; set; }
        public virtual DbSet<FixedInwardChequedump> FixedInwardChequedump { get; set; }
        public virtual DbSet<GLAccountSetup> GLAccountSetup { get; set; }
        public virtual DbSet<InwardChequedump_Trigger> InwardChequedump_Trigger { get; set; }
        public virtual DbSet<InwardChequeImage> InwardChequeImage { get; set; }
        public virtual DbSet<InwardMessages> InwardMessages { get; set; }
        public virtual DbSet<iTellerTimeStamp> iTellerTimeStamp { get; set; }
        public virtual DbSet<KioskCustomerAcctDetails> KioskCustomerAcctDetails { get; set; }
        public virtual DbSet<Kiosks> Kiosks { get; set; }
        public virtual DbSet<LoggedOnUsers> LoggedOnUsers { get; set; }
        public virtual DbSet<LogOnUserRecord> LogOnUserRecord { get; set; }
        public virtual DbSet<MakerChecker> MakerChecker { get; set; }
        public virtual DbSet<messageCounter> messageCounter { get; set; }
        public virtual DbSet<Modules> Modules { get; set; }
        public virtual DbSet<Resources> Resources { get; set; }
        public virtual DbSet<ReturnedChequeImages> ReturnedChequeImages { get; set; }
        public virtual DbSet<ReturnInwardFile> ReturnInwardFile { get; set; }
        public virtual DbSet<RoleResources> RoleResources { get; set; }
        public virtual DbSet<ROLES> ROLES { get; set; }
        public virtual DbSet<ScannerDetail> ScannerDetail { get; set; }
        public virtual DbSet<ScannerStore> ScannerStore { get; set; }
        public virtual DbSet<SettlementTimes> SettlementTimes { get; set; }
        public virtual DbSet<SystemConfiguration> SystemConfiguration { get; set; }
        public virtual DbSet<TillAssignment> TillAssignment { get; set; }
        public virtual DbSet<TillAssignmentHistory> TillAssignmentHistory { get; set; }
        public virtual DbSet<TillManagement> TillManagement { get; set; }
        public virtual DbSet<TillSetup> TillSetup { get; set; }
        public virtual DbSet<TillTransfer> TillTransfer { get; set; }
        public virtual DbSet<TransactionFiles> TransactionFiles { get; set; }
        public virtual DbSet<TransactionsMaster> TransactionsMaster { get; set; }
        public virtual DbSet<TransDetails> TransDetails { get; set; }
        public virtual DbSet<TransferDetails> TransferDetails { get; set; }
        public virtual DbSet<TransferHeader> TransferHeader { get; set; }
        public virtual DbSet<TransferType> TransferType { get; set; }
        public virtual DbSet<TransMaster> TransMaster { get; set; }
        public virtual DbSet<TransMasterDetails> TransMasterDetails { get; set; }
        public virtual DbSet<TransSetup> TransSetup { get; set; }
        public virtual DbSet<TreasuryInterest> TreasuryInterest { get; set; }
        public virtual DbSet<UserActivity> UserActivity { get; set; }
        public virtual DbSet<UserLogins> UserLogins { get; set; }
        public virtual DbSet<USERROLES> USERROLES { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<USERS_IN_GROUP> USERS_IN_GROUP { get; set; }
        public virtual DbSet<accountmandates> accountmandates { get; set; }
        public virtual DbSet<Bank> Bank { get; set; }
        public virtual DbSet<cards> cards { get; set; }
        public virtual DbSet<CautionHeaderFooter> CautionHeaderFooter { get; set; }
        public virtual DbSet<CautionNotice> CautionNotice { get; set; }
        public virtual DbSet<CautionSignatures> CautionSignatures { get; set; }
        public virtual DbSet<ChequeBeneficiary> ChequeBeneficiary { get; set; }
        public virtual DbSet<ChequeCaution> ChequeCaution { get; set; }
        public virtual DbSet<ChequeDetailsCheckLog> ChequeDetailsCheckLog { get; set; }
        public virtual DbSet<ChequeDump_Trigger> ChequeDump_Trigger { get; set; }
        public virtual DbSet<chequeimageuv> chequeimageuv { get; set; }
        public virtual DbSet<ChequesForCashWithdrawal> ChequesForCashWithdrawal { get; set; }
        public virtual DbSet<chq_bene> chq_bene { get; set; }
        public virtual DbSet<ClientScanners> ClientScanners { get; set; }
        public virtual DbSet<CompanyLogo> CompanyLogo { get; set; }
        public virtual DbSet<Currency> Currency { get; set; }
        public virtual DbSet<CurrencySubunit> CurrencySubunit { get; set; }
        public virtual DbSet<InwardChequedump> InwardChequedump { get; set; }
        public virtual DbSet<kioskLogos> kioskLogos { get; set; }
        public virtual DbSet<KioskRejectedCheques> KioskRejectedCheques { get; set; }
        public virtual DbSet<KioskRejectionReasons> KioskRejectionReasons { get; set; }
        public virtual DbSet<KioskReturnedCheques> KioskReturnedCheques { get; set; }
        public virtual DbSet<POSPosting> POSPosting { get; set; }
        public virtual DbSet<ReturnedCheques> ReturnedCheques { get; set; }
        public virtual DbSet<ReturnReasons> ReturnReasons { get; set; }
        public virtual DbSet<scorpion> scorpion { get; set; }
        public virtual DbSet<SystemConfiguration_Trigger> SystemConfiguration_Trigger { get; set; }
        public virtual DbSet<TerminalPosMap> TerminalPosMap { get; set; }
        public virtual DbSet<TillSetupDeleted> TillSetupDeleted { get; set; }
        public virtual DbSet<TillTransferDisapproval> TillTransferDisapproval { get; set; }
        public virtual DbSet<TransactionCodeToDETypeMapping> TransactionCodeToDETypeMapping { get; set; }
        public virtual DbSet<TransDepCounter> TransDepCounter { get; set; }
        public virtual DbSet<TransTypes> TransTypes { get; set; }
        public virtual DbSet<UserBranches> UserBranches { get; set; }
        public virtual DbSet<UserCurrencies> UserCurrencies { get; set; }
        public virtual DbSet<UserSignature> UserSignature { get; set; }
        public virtual DbSet<TerminationInstruction> TerminationInstruction { get; set; }
        public virtual DbSet<TransactionCodes> TransactionCodes { get; set; }
        public virtual DbSet<DiscountedTreasuryProduct> DiscountedTreasuryProduct { get; set; }
        public virtual DbSet<MCCharge> MCCharge { get; set; }
        public virtual DbSet<MCAccount> MCAccount { get; set; }
        public virtual DbSet<TreasuryDetails> TreasuryDetails { get; set; }
        public virtual DbSet<Cheque_Template> Cheque_Template { get; set; }
        public virtual DbSet<DraftIssuedCharges> DraftIssuedCharges { get; set; }
        public virtual DbSet<TreasuryProductCode> TreasuryProductCode { get; set; }
        public virtual DbSet<AccountStament> AccountStament { get; set; }
        public virtual DbSet<TreasuryDealsMaster> TreasuryDealsMaster { get; set; }
        public virtual DbSet<UserTransactionPageAccess> UserTransactionPageAccess { get; set; }
        public virtual DbSet<CustomerDetails> CustomerDetails { get; set; }
        public virtual DbSet<PreLiquidatedDeal> PreLiquidatedDeal { get; set; }
        public virtual DbSet<TillTransferIMAL> TillTransferIMAL { get; set; }
        public virtual DbSet<OutwardChequeDetails> OutwardChequeDetails { get; set; }
        public virtual DbSet<ManagerChequeIssuanceDetails> ManagerChequeIssuanceDetails { get; set; }
        public virtual DbSet<BranchAccounts> BranchAccounts { get; set; }
    }
}
