//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iTellerBranch.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class KioskRejectedCheques
    {
        public int Id { get; set; }
        public string KioskID { get; set; }
        public Nullable<decimal> ChequeRef { get; set; }
        public string RejectionReason { get; set; }
    }
}
