//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iTellerBranch.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class KioskCustomerAcctDetails
    {
        public int Id { get; set; }
        public string AccountNo { get; set; }
        public string AccountName { get; set; }
        public string EmailAddress { get; set; }
        public string PhoneNo { get; set; }
        public Nullable<decimal> CautionAmount { get; set; }
        public Nullable<int> CautionAge { get; set; }
        public string PAN { get; set; }
        public byte[] Signature { get; set; }
        public Nullable<int> CurrencyCode { get; set; }
        public Nullable<System.DateTime> LastDateModified { get; set; }
        public string BranchCode { get; set; }
    }
}
