//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iTellerBranch.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogOnUserRecord
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public string TillStatus { get; set; }
        public string TellerId { get; set; }
        public Nullable<decimal> CreditAmount { get; set; }
        public Nullable<decimal> DebitAmount { get; set; }
        public Nullable<System.TimeSpan> TimeOpened { get; set; }
        public string UserName { get; set; }
        public string UserTillBranch { get; set; }
        public Nullable<decimal> LocalCurrencyAmount { get; set; }
        public string UserRole { get; set; }
        public string ProfileStartTime { get; set; }
        public string ProfileEndTime { get; set; }
        public string UserBranch { get; set; }
    }
}
