//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iTellerBranch.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManagerChequeIssuanceDetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ManagerChequeIssuanceDetails()
        {
            this.DraftIssuedCharges = new HashSet<DraftIssuedCharges>();
        }
    
        public int ID { get; set; }
        public string AccountNumber { get; set; }
        public string AccountName { get; set; }
        public string DraftNumber { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string ChequeNumber { get; set; }
        public Nullable<int> TemplateCode { get; set; }
        public Nullable<bool> Printed { get; set; }
        public string PaymentDetails { get; set; }
        public string BeneficiaryName { get; set; }
        public string PaidStatus { get; set; }
        public string BeneficiaryAccount { get; set; }
        public string TransactionReference { get; set; }
        public Nullable<bool> Approved { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> WhenApproved { get; set; }
        public string DissaprovedBy { get; set; }
        public Nullable<System.DateTime> WhenDissapproved { get; set; }
        public string CBAResponse { get; set; }
        public string CBAResponseCode { get; set; }
        public string BranchCode { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<int> CurrencyCode { get; set; }
        public Nullable<System.DateTime> ValueDate { get; set; }
        public string RepurchaseRefId { get; set; }
        public string DissapprovalReason { get; set; }
        public Nullable<System.DateTime> DebitValueDate { get; set; }
        public Nullable<decimal> ChargeAmount { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DraftIssuedCharges> DraftIssuedCharges { get; set; }
    }
}
