//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iTellerBranch.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class MCCharge
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MCCharge()
        {
            this.DraftIssuedCharges = new HashSet<DraftIssuedCharges>();
        }
    
        public int ID { get; set; }
        public string ChargeCode { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> ChargeWithdrawn { get; set; }
        public Nullable<decimal> MinimumCharge { get; set; }
        public string ChargeAccount { get; set; }
        public Nullable<bool> IsPercentage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DraftIssuedCharges> DraftIssuedCharges { get; set; }
    }
}
