//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iTellerBranch.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class messageCounter
    {
        public int msgid { get; set; }
        public Nullable<bool> freshItems { get; set; }
        public string currency { get; set; }
        public Nullable<int> itemCount { get; set; }
        public Nullable<decimal> TotalValue { get; set; }
        public Nullable<System.DateTime> generationTime { get; set; }
        public Nullable<bool> sent { get; set; }
        public Nullable<int> SettlementWindowID { get; set; }
        public Nullable<int> failedItems { get; set; }
    }
}
