//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iTellerBranch.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutwardChequeDetails
    {
        public string CreditAccountNumber { get; set; }
        public string CreditAccountName { get; set; }
        public string DebitAccountNumber { get; set; }
        public string DebitAccountName { get; set; }
        public Nullable<decimal> CreditAmount { get; set; }
        public Nullable<int> CurrencyCode { get; set; }
        public string BankAddress { get; set; }
        public string BankCode { get; set; }
        public string DrawalName { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<bool> Approved { get; set; }
        public Nullable<System.DateTime> DebitValueDate { get; set; }
        public int Id { get; set; }
        public string ChequeNumber { get; set; }
        public string TellerName { get; set; }
        public string BranchCode { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> WhenApproved { get; set; }
        public Nullable<System.DateTime> DisapprovedBy { get; set; }
        public Nullable<System.DateTime> WhenDissaprroved { get; set; }
        public string DisapprovalReason { get; set; }
        public string TransactionReference { get; set; }
        public string CBAResponse { get; set; }
        public string CBAResponseCode { get; set; }
    }
}
