//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iTellerBranch.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class POSPosting
    {
        public int ID { get; set; }
        public string POSId { get; set; }
        public string TerminalId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string AccountNo { get; set; }
        public Nullable<System.DateTime> PostTime { get; set; }
        public int Deliver { get; set; }
        public string TranType { get; set; }
    }
}
