//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iTellerBranch.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resources
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Resources()
        {
            this.RoleResources = new HashSet<RoleResources>();
        }
    
        public int ResourceId { get; set; }
        public string ResourceName { get; set; }
        public string ResourceDesc { get; set; }
        public Nullable<int> ModuleId { get; set; }
        public Nullable<int> Sequence { get; set; }
        public string AppId { get; set; }
        public Nullable<bool> NeedMakerChecker { get; set; }
        public string TableName { get; set; }
        public Nullable<bool> Show { get; set; }
        public Nullable<int> ShowMenu { get; set; }
        public Nullable<int> SubMenu { get; set; }
        public string Path { get; set; }
        public string FontIcon { get; set; }
    
        public virtual Modules Modules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoleResources> RoleResources { get; set; }
    }
}
