//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iTellerBranch.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReturnInwardFile
    {
        public int id { get; set; }
        public System.DateTime fileDate { get; set; }
        public int Session { get; set; }
        public int FileID { get; set; }
        public string fileName { get; set; }
        public string Currency { get; set; }
        public Nullable<int> SettlementWindowID { get; set; }
        public Nullable<System.DateTime> SettlementTime { get; set; }
    }
}
