//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iTellerBranch.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReturnReasons
    {
        public int Id { get; set; }
        public string ReasonCode { get; set; }
        public string ReasonDescription { get; set; }
        public string CBACode { get; set; }
    }
}
