//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iTellerBranch.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScannerDetail
    {
        public int ID { get; set; }
        public string ClientID { get; set; }
        public string ScannerType { get; set; }
        public string ScannerSerialNo { get; set; }
        public bool Deleted { get; set; }
    }
}
