//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iTellerBranch.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScannerStore
    {
        public int ID { get; set; }
        public string SCANNER { get; set; }
        public string FOLDER { get; set; }
        public string APPLICATION_NAME { get; set; }
        public bool LITE { get; set; }
        public Nullable<bool> DELETE { get; set; }
    }
}
