//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iTellerBranch.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TillManagement
    {
        public int Id { get; set; }
        public string TransactionBranch { get; set; }
        public string TellerId { get; set; }
        public string Status { get; set; }
        public string Comments { get; set; }
        public string IsHeadTeller { get; set; }
        public string User { get; set; }
        public Nullable<bool> Approve { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<bool> IsClosed { get; set; }
        public string Event { get; set; }
        public string CBAResponse { get; set; }
        public Nullable<decimal> ClosingBalance { get; set; }
        public Nullable<decimal> ShortageOverageAmount { get; set; }
    }
}
