//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iTellerBranch.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TillSetupDeleted
    {
        public int ID { get; set; }
        public string TillNos { get; set; }
        public string TillDesc { get; set; }
        public string GLAcctNo { get; set; }
        public bool IsVault { get; set; }
        public string SortCode { get; set; }
        public string GLAcctName { get; set; }
        public Nullable<int> GLAcctCurrency { get; set; }
        public Nullable<System.DateTime> DateDeleted { get; set; }
        public string WhoDeleted { get; set; }
    }
}
