//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iTellerBranch.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TillTransfer
    {
        public int Id { get; set; }
        public Nullable<long> TranId { get; set; }
        public Nullable<System.DateTime> TransferDate { get; set; }
        public int CurrencyCode { get; set; }
        public string ReceiverTillNo { get; set; }
        public string ReceiverUser { get; set; }
        public string GiverTillNo { get; set; }
        public string GiverUser { get; set; }
        public string CashierID { get; set; }
        public decimal Amount { get; set; }
        public Nullable<decimal> AmountReleased { get; set; }
        public Nullable<bool> IsFufilled { get; set; }
        public Nullable<bool> Accepted { get; set; }
        public Nullable<int> TransferMode { get; set; }
        public string Branch { get; set; }
        public string CBA { get; set; }
    
        public virtual CashDenomination CashDenomination { get; set; }
        public virtual TransactionsMaster TransactionsMaster { get; set; }
    }
}
