//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iTellerBranch.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionFiles
    {
        public int Id { get; set; }
        public Nullable<long> TranId { get; set; }
        public string FileName { get; set; }
        public string UserId { get; set; }
        public string Branch { get; set; }
        public Nullable<int> TotalCount { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<System.DateTime> DateUploaded { get; set; }
    
        public virtual TransactionsMaster TransactionsMaster { get; set; }
    }
}
