//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iTellerBranch.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransferHeader
    {
        public int Id { get; set; }
        public Nullable<long> TranId { get; set; }
        public string InstrumentNumber { get; set; }
        public Nullable<decimal> ApplicableCharge { get; set; }
        public Nullable<bool> IsBulkTran { get; set; }
        public string ChargeType { get; set; }
    }
}
