//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iTellerBranch.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransferDetails
    {
        public int Id { get; set; }
        public Nullable<long> TranId { get; set; }
        public string BenAccountNumber { get; set; }
        public string BenAccountName { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Narration { get; set; }
        public Nullable<decimal> ApplicableCharge { get; set; }
        public string TransRef { get; set; }
        public Nullable<bool> Posted { get; set; }
        public string CBAResponse { get; set; }
        public string CBAResponseCode { get; set; }
    }
}
