//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iTellerBranch.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransMasterDetails
    {
        public int Id { get; set; }
        public Nullable<long> TranId { get; set; }
        public Nullable<int> Counter { get; set; }
        public Nullable<decimal> Amount { get; set; }
    }
}
