//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iTellerBranch.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TreasuryDetails
    {
        public int ID { get; set; }
        public Nullable<long> TranId { get; set; }
        public string AccountName { get; set; }
        public string AccountNumber { get; set; }
        public string DealId { get; set; }
        public string CrDr { get; set; }
        public string Naration { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string TransRef { get; set; }
        public Nullable<bool> Posted { get; set; }
        public string CBAResponse { get; set; }
        public string CBAResponseCode { get; set; }
        public Nullable<bool> IsReversed { get; set; }
    
        public virtual TransactionsMaster TransactionsMaster { get; set; }
    }
}
