//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iTellerBranch.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLogins
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public string Password { get; set; }
        public Nullable<bool> Active { get; set; }
        public string Staffid { get; set; }
        public string Firstname { get; set; }
        public string Middlename { get; set; }
        public string Lastname { get; set; }
        public string Email { get; set; }
        public Nullable<int> LoginAttempts { get; set; }
        public Nullable<System.DateTime> DateLastModified { get; set; }
        public Nullable<bool> Successful { get; set; }
    }
}
