//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iTellerBranch.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTransactionPageAccess
    {
        public long Id { get; set; }
        public Nullable<int> TranId { get; set; }
        public Nullable<System.DateTime> DateAccessed { get; set; }
        public Nullable<bool> IsActiveOnPage { get; set; }
        public string UserId { get; set; }
    
        public virtual TreasuryDealsMaster TreasuryDealsMaster { get; set; }
    }
}
