//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iTellerBranch.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.TillAssignment = new HashSet<TillAssignment>();
        }
    
        public int Id { get; set; }
        public string UserId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string UserLevel { get; set; }
        public Nullable<bool> Locked { get; set; }
        public Nullable<System.DateTime> LowerLimit { get; set; }
        public Nullable<System.DateTime> UpperLimit { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<bool> Expired { get; set; }
        public Nullable<int> ValidDays { get; set; }
        public string Email { get; set; }
        public string BankCode { get; set; }
        public Nullable<bool> Supervisory { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> LastLogingTime { get; set; }
        public Nullable<System.DateTime> DateLastModified { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TillAssignment> TillAssignment { get; set; }
    }
}
